#!/bin/bash

source ./0compose/utils.sh
source ./0compose/constant.sh

c=$1
shift;

case "$c" in
  run)
    ./0compose/run.sh "${@}"
    ;;

  logs)
    ./0compose/logs.sh "${@}"
    ;;

  exec)
    ./0compose/exec.sh "${@}"
    ;;

  rm)
    docker-compose -f ./0compose/docker-compose.dev.yml stop
    docker-compose -f ./0compose/docker-compose.dev.yml rm -f
    ;;

  *)
    echo $"Usage: $0 {run|logs|exec|rm}"
    exit 1

esac
