version: "2"

services:

  webpack:
    build:
      context: ../source
      dockerfile: Dockerfile
    volumes:
      - ../source/src:/home/nodejs/app/src
      - ../source/build:/home/nodejs/app/build
      - ../source/package.json:/home/nodejs/app/package.json
      - ../source/npm-shrinkwrap.json:/home/nodejs/app/npm-shrinkwrap.json
    command: bash -c "echo 'helloword'; tail -f /dev/null"

# networks:
  # back-tier:
  # front-tier:
# volumes:
  # db-data:
